# Generated by Django 5.1.7 on 2025-03-18 20:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=1024)),
                ('whole_pages', models.DecimalField(decimal_places=0, max_digits=5)),
                ('read_pages', models.DecimalField(decimal_places=0, max_digits=5)),
                ('progress', models.FloatField()),
                ('pid', models.CharField(default=uuid.UUID('69414661-f499-4baf-b481-6f450df526da'), max_length=25, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.category')),
            ],
            options={
                'indexes': [models.Index(fields=['title', 'pid'], name='plan_book_title_4c7b2f_idx')],
            },
        ),
    ]
